name: Generate Minified Bookmarklet Script

on:
  push:
    branches:
      - main

jobs:
  build_minified_script:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push changes back to the repo
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install UglifyJS
        run: npm install uglify-js # Installs locally to node_modules

      - name: Minify rsvp-reader.js to docs/
        run: ./node_modules/.bin/uglifyjs rsvp-reader.js -o docs/rsvp-reader.min.js -c -m --toplevel

      - name: Commit and push docs/rsvp-reader.min.js
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # Check if the target file was actually created/modified before adding
          if [ -f "docs/rsvp-reader.min.js" ]; then
            git add docs/rsvp-reader.min.js
            if git diff --staged --quiet; then
              echo "No changes to docs/rsvp-reader.min.js to commit."
            else
              git commit -m 'Workflow: Update docs/rsvp-reader.min.js for bookmarklet'
              git push
              echo "docs/rsvp-reader.min.js committed and pushed."
            fi
          else
            echo "docs/rsvp-reader.min.js was not created. Skipping commit."
          fi
