name: Build Chrome Extension and Place in Docs

on:
  push:
    branches:
      - main

jobs:
  build_extension:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push changes back to the repo
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        # JSDOM is no longer needed here, so npm install jsdom can be removed if it was present.

      - name: Create manifest.json
        run: |
          cat <<EOF > manifest.json
          {
            "manifest_version": 3,
            "name": "RSVP Reader Extension",
            "version": "1.0.1", 
            "description": "Reads selected text using RSVP method.",
            "icons": { "128": "rsvp.png" },
            "permissions": ["activeTab", "scripting"],
            "action": {
              "default_popup": "popup.html",
              "default_icon": { "128": "rsvp.png" }
            }
          }
          EOF
          echo "manifest.json created."

      - name: Create popup.html
        run: |
          cat <<EOF > popup.html
          <!DOCTYPE html>
          <html><head><title>RSVP Reader</title><meta charset="utf-8">
          <style>
            body { width: 200px; font-family: sans-serif; text-align: center; padding: 10px;}
            button { width: 100%; padding: 10px; margin-top: 5px; background-color: #007bff; color: white; border: none; border-radius: 3px; cursor: pointer; }
            button:hover { background-color: #0056b3; }
          </style></head>
          <body><p>Click to activate RSVP Reader on the current page.</p>
          <button id="activateReader">Activate RSVP</button><script src="popup.js"></script></body></html>
          EOF
          echo "popup.html created."

      - name: Create popup.js
        run: |
          cat <<EOF > popup.js
          document.getElementById('activateReader').addEventListener('click', () => {
            chrome.tabs.query({active: true, currentWindow: true}, (tabs) => {
              if (tabs[0] && tabs[0].id) {
                chrome.scripting.executeScript({
                  target: {tabId: tabs[0].id}, files: ['rsvp-reader.js']
                }).then(() => {
                  console.log("RSVP Reader script injected."); window.close();
                }).catch(err => console.error("Error injecting script: ", err));
              } else { console.error("Could not get active tab ID for scripting."); }
            });
          });
          EOF
          echo "popup.js created."

      - name: Create docs directory if it doesn't exist
        run: mkdir -p docs # Ensures docs/ directory exists before placing zip file into it

      - name: Zip the extension into docs/
        run: zip docs/rsvp-reader-extension.zip manifest.json popup.html popup.js rsvp-reader.js rsvp.png

      - name: Commit and push extension files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # Add the zip file and the extension source files
          git add docs/rsvp-reader-extension.zip manifest.json popup.html popup.js
          if git diff --staged --quiet; then
            echo "No changes to Chrome extension files to commit."
          else
            git commit -m 'Workflow: Build Chrome extension and place in docs/'
            git push
            echo "Chrome extension files committed and pushed."
          fi
